language: node_js
before_script:
  - export GRAPHY_PACKAGE_PREFIX="$(dirname $(dirname $(nvm which current)))"
  - export GRAPHY_SKIP_DBR_TESTS=1
  - export GRAPHY_USE_NVM=1
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
